import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { useTranslation } from 'react-i18next'

import { SystemLogTerminal } from '@/components/SystemLogTerminal'
import { SimInstanceCard } from '@/components/step2/SimInstanceCard'
import { AgentPersonaCard } from '@/components/step2/AgentPersonaCard'
import { PlatformConfigCard } from '@/components/step2/PlatformConfigCard'
import { ActivationCard } from '@/components/step2/ActivationCard'
import { SetupCompleteCard } from '@/components/step2/SetupCompleteCard'
import { ProfileModal } from '@/components/step2/ProfileModal'
import {
  prepareSimulation,
  getPrepareStatus,
  getSimulationProfilesRealtime,
  getSimulationConfigRealtime,
} from '@/lib/api/simulation'
import type { ProjectData, SystemLog } from '@/lib/process-types'
import type { Profile, SimulationConfig } from '@/lib/step2-types'
import type { WorkflowStatus } from '@/components/WorkflowLayout'

interface Step2Props {
  simulationId: string
  projectData: ProjectData | null
  systemLogs: SystemLog[]
  addLog: (msg: string) => void
  onUpdateStatus: (status: WorkflowStatus) => void
  onGoBack: () => void
  onNextStep: (params: { maxRounds?: number }) => void
}

/** 步骤二：环境搭建编排器（准备/人设/配置 三路轮询 + 五张卡片）。 */
export function Step2EnvSetup({
  simulationId,
  projectData,
  systemLogs,
  addLog,
  onUpdateStatus,
  onGoBack,
  onNextStep,
}: Step2Props) {
  const { t } = useTranslation()

  const [phase, setPhase] = useState(0) // 0 初始化 / 1 人设 / 2 配置 / 4 完成
  const [taskId, setTaskId] = useState<string | null>(null)
  const [prepareProgress, setPrepareProgress] = useState(0)
  const [currentStage, setCurrentStage] = useState('')
  const [profiles, setProfiles] = useState<Profile[]>([])
  const [expectedTotal, setExpectedTotal] = useState<number | null>(null)
  const [simulationConfig, setSimulationConfig] = useState<SimulationConfig | null>(null)
  const [selectedProfile, setSelectedProfile] = useState<Profile | null>(null)
  const [useCustomRounds, setUseCustomRounds] = useState(false)
  const [customMaxRounds, setCustomMaxRounds] = useState(40)

  // 计时器与可变引用
  const pollTimer = useRef<ReturnType<typeof setInterval> | null>(null)
  const profilesTimer = useRef<ReturnType<typeof setInterval> | null>(null)
  const configTimer = useRef<ReturnType<typeof setInterval> | null>(null)
  const taskIdRef = useRef<string | null>(null)
  const profilesRef = useRef<Profile[]>([])
  const expectedRef = useRef<number | null>(null)
  const initedRef = useRef(false)
  // 日志去重
  const lastMsg = useRef('')
  const lastProfileCount = useRef(0)
  const lastConfigStage = useRef('')

  // 从配置推算自动轮数（不小于 40）
  const autoGeneratedRounds = useMemo(() => {
    const tc = simulationConfig?.time_config
    if (!tc?.total_simulation_hours || !tc?.minutes_per_round) return null
    return Math.max(Math.floor((tc.total_simulation_hours * 60) / tc.minutes_per_round), 40)
  }, [simulationConfig])

  const getAgentUsername = useCallback((agentId: number) => {
    const p = profilesRef.current
    if (p && p.length > agentId && agentId >= 0) {
      return p[agentId]?.username || `agent_${agentId}`
    }
    return `agent_${agentId}`
  }, [])

  const stopPolling = useCallback(() => {
    if (pollTimer.current) clearInterval(pollTimer.current)
    pollTimer.current = null
  }, [])
  const stopProfilesPolling = useCallback(() => {
    if (profilesTimer.current) clearInterval(profilesTimer.current)
    profilesTimer.current = null
  }, [])
  const stopConfigPolling = useCallback(() => {
    if (configTimer.current) clearInterval(configTimer.current)
    configTimer.current = null
  }, [])

  const fetchProfilesRealtime = useCallback(async () => {
    if (!simulationId) return
    try {
      const res = await getSimulationProfilesRealtime(simulationId, 'reddit')
      if (res.success && res.data) {
        const list: Profile[] = res.data.profiles || []
        profilesRef.current = list
        setProfiles(list)
        if (res.data.total_expected) {
          expectedRef.current = res.data.total_expected
          setExpectedTotal(res.data.total_expected)
        }
        const count = list.length
        if (count > 0 && count !== lastProfileCount.current) {
          lastProfileCount.current = count
          const total = expectedRef.current || '?'
          const latest = list[count - 1]
          const name = latest?.name || latest?.username || `Agent_${count}`
          if (count === 1) addLog(t('log.startGeneratingAgentProfiles'))
          addLog(
            t('log.agentProfile', {
              current: count,
              total,
              name,
              profession: latest?.profession || t('step2.unknownProfession'),
            }),
          )
          if (expectedRef.current && count >= expectedRef.current) {
            addLog(t('log.allProfilesComplete', { count }))
          }
        }
      }
    } catch (err) {
      console.warn('获取 Profiles 失败:', err)
    }
  }, [addLog, simulationId, t])

  const fetchConfigRealtime = useCallback(async () => {
    if (!simulationId) return
    try {
      const res = await getSimulationConfigRealtime(simulationId)
      if (!res.success || !res.data) return
      const data = res.data
      if (data.generation_stage && data.generation_stage !== lastConfigStage.current) {
        lastConfigStage.current = data.generation_stage
        if (data.generation_stage === 'generating_profiles')
          addLog(t('log.generatingAgentProfileConfig'))
        else if (data.generation_stage === 'generating_config') addLog(t('log.generatingLLMConfig'))
      }
      if (data.config_generated && data.config) {
        setSimulationConfig(data.config)
        addLog(t('log.configComplete'))
        if (data.summary) {
          addLog(t('log.configSummaryAgents', { count: data.summary.total_agents }))
          addLog(t('log.configSummaryHours', { hours: data.summary.simulation_hours }))
          addLog(t('log.configSummaryPosts', { count: data.summary.initial_posts_count }))
          addLog(t('log.configSummaryTopics', { count: data.summary.hot_topics_count }))
          addLog(
            t('log.configSummaryPlatforms', {
              twitter: data.summary.has_twitter_config ? '✓' : '✗',
              reddit: data.summary.has_reddit_config ? '✓' : '✗',
            }),
          )
        }
        stopConfigPolling()
        setPhase(4)
        addLog(t('log.envSetupComplete'))
        onUpdateStatus('completed')
      }
    } catch (err) {
      console.warn('获取 Config 失败:', err)
    }
  }, [addLog, onUpdateStatus, simulationId, stopConfigPolling, t])

  const startConfigPolling = useCallback(() => {
    if (configTimer.current) return
    addLog(t('log.startGeneratingConfig'))
    configTimer.current = setInterval(fetchConfigRealtime, 2000)
  }, [addLog, fetchConfigRealtime, t])

  const loadPreparedData = useCallback(async () => {
    setPhase(2)
    addLog(t('log.loadingExistingConfig'))
    await fetchProfilesRealtime()
    addLog(t('log.loadedAgentProfiles', { count: profilesRef.current.length }))
    try {
      const res = await getSimulationConfigRealtime(simulationId)
      if (res.success && res.data) {
        if (res.data.config_generated && res.data.config) {
          setSimulationConfig(res.data.config)
          addLog(t('log.configLoadSuccess'))
          if (res.data.summary) {
            addLog(t('log.configSummaryAgents', { count: res.data.summary.total_agents }))
            addLog(t('log.configSummaryHours', { hours: res.data.summary.simulation_hours }))
            addLog(t('log.configSummaryPostsAlt', { count: res.data.summary.initial_posts_count }))
          }
          addLog(t('log.envSetupComplete'))
          setPhase(4)
          onUpdateStatus('completed')
        } else {
          addLog(t('log.configGenerating'))
          startConfigPolling()
        }
      }
    } catch (err) {
      addLog(t('log.loadConfigFailed', { error: (err as Error).message }))
      onUpdateStatus('error')
    }
  }, [addLog, fetchProfilesRealtime, onUpdateStatus, simulationId, startConfigPolling, t])

  const pollPrepareStatus = useCallback(async () => {
    if (!taskIdRef.current && !simulationId) return
    try {
      const res = await getPrepareStatus({
        task_id: taskIdRef.current,
        simulation_id: simulationId,
      })
      if (!res.success || !res.data) return
      const data = res.data
      setPrepareProgress(data.progress || 0)

      if (data.progress_detail) {
        const detail = data.progress_detail
        setCurrentStage(detail.current_stage_name || '')
        const logKey = `${detail.current_stage}-${detail.current_item}-${detail.total_items}`
        if (logKey !== lastMsg.current && detail.item_description) {
          lastMsg.current = logKey
          const stageInfo = `[${detail.stage_index}/${detail.total_stages}]`
          addLog(
            detail.total_items > 0
              ? `${stageInfo} ${detail.current_stage_name}: ${detail.current_item}/${detail.total_items} - ${detail.item_description}`
              : `${stageInfo} ${detail.current_stage_name}: ${detail.item_description}`,
          )
        }
      } else if (data.message) {
        const match = data.message.match(/\[(\d+)\/(\d+)\]\s*([^:]+)/)
        if (match) setCurrentStage(match[3].trim())
        if (data.message !== lastMsg.current) {
          lastMsg.current = data.message
          addLog(data.message)
        }
      }

      if (data.status === 'completed' || data.status === 'ready' || data.already_prepared) {
        addLog(t('log.prepareComplete'))
        stopPolling()
        stopProfilesPolling()
        await loadPreparedData()
      } else if (data.status === 'failed') {
        addLog(t('log.prepareFailedWithError', { error: data.error || t('common.unknownError') }))
        stopPolling()
        stopProfilesPolling()
      }
    } catch (err) {
      console.warn('轮询状态失败:', err)
    }
  }, [addLog, loadPreparedData, simulationId, stopPolling, stopProfilesPolling, t])

  const startPrepare = useCallback(async () => {
    if (!simulationId) {
      addLog(t('log.errorMissingSimId'))
      onUpdateStatus('error')
      return
    }
    setPhase(1)
    addLog(t('log.simInstanceCreated', { id: simulationId }))
    addLog(t('log.preparingSimEnv'))
    onUpdateStatus('processing')
    try {
      const res = await prepareSimulation({
        simulation_id: simulationId,
        use_llm_for_profiles: true,
        parallel_profile_count: 5,
      })
      if (res.success && res.data) {
        if (res.data.already_prepared) {
          addLog(t('log.detectedExistingPrep'))
          await loadPreparedData()
          return
        }
        taskIdRef.current = res.data.task_id
        setTaskId(res.data.task_id)
        addLog(t('log.prepareTaskStarted'))
        addLog(t('log.prepareTaskId', { taskId: res.data.task_id }))
        if (res.data.expected_entities_count) {
          expectedRef.current = res.data.expected_entities_count
          setExpectedTotal(res.data.expected_entities_count)
          addLog(t('log.graphEntitiesFound', { count: res.data.expected_entities_count }))
          if (res.data.entity_types?.length) {
            addLog(t('log.entityTypes', { types: res.data.entity_types.join(', ') }))
          }
        }
        addLog(t('log.startPollingProgress'))
        pollTimer.current = setInterval(pollPrepareStatus, 2000)
        profilesTimer.current = setInterval(fetchProfilesRealtime, 3000)
      } else {
        addLog(t('log.prepareFailed', { error: res.error || t('common.unknownError') }))
        onUpdateStatus('error')
      }
    } catch (err) {
      addLog(t('log.prepareException', { error: (err as Error).message }))
      onUpdateStatus('error')
    }
  }, [
    addLog,
    fetchProfilesRealtime,
    loadPreparedData,
    onUpdateStatus,
    pollPrepareStatus,
    simulationId,
    t,
  ])

  // 阶段切换：进入配置生成阶段时启动配置轮询
  useEffect(() => {
    if (currentStage === '生成Agent人设' || currentStage === 'generating_profiles') {
      setPhase((p) => (p < 1 ? 1 : p))
    } else if (currentStage === '生成模拟配置' || currentStage === 'generating_config') {
      setPhase((p) => (p < 2 ? 2 : p))
      startConfigPolling()
    }
  }, [currentStage, startConfigPolling])

  // 挂载时启动准备流程（仅一次）
  useEffect(() => {
    if (initedRef.current) return
    initedRef.current = true
    if (simulationId) {
      addLog(t('log.step2Init'))
      void startPrepare()
    }
    return () => {
      stopPolling()
      stopProfilesPolling()
      stopConfigPolling()
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const handleStart = () => {
    if (useCustomRounds) {
      addLog(t('log.startSimCustomRounds', { rounds: customMaxRounds }))
      onNextStep({ maxRounds: customMaxRounds })
    } else {
      addLog(t('log.startSimAutoRounds', { rounds: autoGeneratedRounds }))
      onNextStep({})
    }
  }

  return (
    <div className="bg-muted/30 flex h-full flex-col overflow-hidden">
      <div className="flex flex-1 flex-col gap-5 overflow-y-auto p-6">
        <SimInstanceCard
          phase={phase}
          projectData={projectData}
          simulationId={simulationId}
          taskId={taskId}
        />
        <AgentPersonaCard
          phase={phase}
          profiles={profiles}
          expectedTotal={expectedTotal}
          prepareProgress={prepareProgress}
          onSelectProfile={setSelectedProfile}
        />
        <PlatformConfigCard phase={phase} config={simulationConfig} />
        <ActivationCard
          phase={phase}
          config={simulationConfig}
          getAgentUsername={getAgentUsername}
        />
        <SetupCompleteCard
          phase={phase}
          hasConfig={!!simulationConfig}
          autoGeneratedRounds={autoGeneratedRounds}
          useCustomRounds={useCustomRounds}
          setUseCustomRounds={setUseCustomRounds}
          customMaxRounds={customMaxRounds}
          setCustomMaxRounds={setCustomMaxRounds}
          onBack={onGoBack}
          onStart={handleStart}
        />
      </div>

      <SystemLogTerminal logs={systemLogs} badge={simulationId || 'NO_SIMULATION'} />

      <ProfileModal profile={selectedProfile} onClose={() => setSelectedProfile(null)} />
    </div>
  )
}
