import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { useTranslation } from 'react-i18next'

import {
  Loader2,
  CheckCircle2,
  Code,
  Sparkles,
  ArrowRight,
  ArrowLeft,
  RefreshCw,
  Compass,
  Megaphone,
} from 'lucide-react'

import { SystemLogTerminal } from '@/components/SystemLogTerminal'
import { StepCard } from '@/components/StepCard'
import { SimInstanceCard } from '@/components/step2/SimInstanceCard'
import { PlatformConfigCard } from '@/components/step2/PlatformConfigCard'
import { ProfileModal } from '@/components/step2/ProfileModal'
import { PersonaBehavior } from '@/components/step2/PersonaBehavior'
import { RoundsControl } from '@/components/step2/RoundsControl'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { CollapsibleHeader } from '@/components/ui/collapsible-header'
import { SoftBadge } from '@/components/ui/soft-badge'
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip'
import {
  prepareSimulation,
  getPrepareStatus,
  getSimulation,
  getSimulationProfilesRealtime,
  getSimulationConfigRealtime,
} from '@/lib/api/simulation'
import type { ProjectData, SystemLog } from '@/lib/process-types'
import type { AgentConfig, Profile, SimulationConfig } from '@/lib/step2-types'
import type { WorkflowStatus } from '@/components/WorkflowLayout'

interface Step2Props {
  simulationId: string
  projectData: ProjectData | null
  systemLogs: SystemLog[]
  addLog: (msg: string) => void
  onUpdateStatus: (status: WorkflowStatus) => void
  onGoBack: () => void
  onNextStep: (params: { maxRounds?: number }) => void
}

/** 步骤二：环境搭建编排器（准备/人设/配置 三路轮询 + 五张卡片）。 */
export function Step2EnvSetup({
  simulationId,
  projectData,
  systemLogs,
  addLog,
  onUpdateStatus,
  onGoBack,
  onNextStep,
}: Step2Props) {
  const { t } = useTranslation()

  const [phase, setPhase] = useState(0) // 0 初始化 / 1 人设 / 2 配置 / 4 完成
  const [taskId, setTaskId] = useState<string | null>(null)
  const [prepareProgress, setPrepareProgress] = useState(0)
  const [currentStage, setCurrentStage] = useState('')
  const [profiles, setProfiles] = useState<Profile[]>([])
  const [expectedTotal, setExpectedTotal] = useState<number | null>(null)
  const [simulationConfig, setSimulationConfig] = useState<SimulationConfig | null>(null)
  const [selectedProfile, setSelectedProfile] = useState<Profile | null>(null)
  const [useCustomRounds, setUseCustomRounds] = useState(false)
  const [customMaxRounds, setCustomMaxRounds] = useState(40)
  const [backstageOpen, setBackstageOpen] = useState(false)

  // 计时器与可变引用
  const pollTimer = useRef<ReturnType<typeof setInterval> | null>(null)
  const profilesTimer = useRef<ReturnType<typeof setInterval> | null>(null)
  const configTimer = useRef<ReturnType<typeof setInterval> | null>(null)
  const taskIdRef = useRef<string | null>(null)
  const profilesRef = useRef<Profile[]>([])
  const expectedRef = useRef<number | null>(null)
  const initedRef = useRef(false)
  // 日志去重
  const lastMsg = useRef('')
  const lastProfileCount = useRef(0)
  const lastConfigStage = useRef('')

  // 从配置推算自动轮数（不小于 40）
  const autoGeneratedRounds = useMemo(() => {
    const tc = simulationConfig?.time_config
    if (!tc?.total_simulation_hours || !tc?.minutes_per_round) return null
    return Math.max(Math.floor((tc.total_simulation_hours * 60) / tc.minutes_per_round), 40)
  }, [simulationConfig])

  const stopPolling = useCallback(() => {
    if (pollTimer.current) clearInterval(pollTimer.current)
    pollTimer.current = null
  }, [])
  const stopProfilesPolling = useCallback(() => {
    if (profilesTimer.current) clearInterval(profilesTimer.current)
    profilesTimer.current = null
  }, [])
  const stopConfigPolling = useCallback(() => {
    if (configTimer.current) clearInterval(configTimer.current)
    configTimer.current = null
  }, [])

  const fetchProfilesRealtime = useCallback(async () => {
    if (!simulationId) return
    try {
      const res = await getSimulationProfilesRealtime(simulationId, 'reddit')
      if (res.success && res.data) {
        const list: Profile[] = res.data.profiles || []
        profilesRef.current = list
        setProfiles(list)
        if (res.data.total_expected) {
          expectedRef.current = res.data.total_expected
          setExpectedTotal(res.data.total_expected)
        }
        const count = list.length
        if (count > 0 && count !== lastProfileCount.current) {
          lastProfileCount.current = count
          const total = expectedRef.current || '?'
          const latest = list[count - 1]
          const name = latest?.name || latest?.username || `Agent_${count}`
          if (count === 1) addLog(t('log.startGeneratingAgentProfiles'))
          addLog(
            t('log.agentProfile', {
              current: count,
              total,
              name,
              profession: latest?.profession || t('step2.unknownProfession'),
            }),
          )
          if (expectedRef.current && count >= expectedRef.current) {
            addLog(t('log.allProfilesComplete', { count }))
          }
        }
      }
    } catch (err) {
      console.warn('获取 Profiles 失败:', err)
    }
  }, [addLog, simulationId, t])

  const fetchConfigRealtime = useCallback(async () => {
    if (!simulationId) return
    try {
      const res = await getSimulationConfigRealtime(simulationId)
      if (!res.success || !res.data) return
      const data = res.data
      if (data.generation_stage && data.generation_stage !== lastConfigStage.current) {
        lastConfigStage.current = data.generation_stage
        if (data.generation_stage === 'generating_profiles')
          addLog(t('log.generatingAgentProfileConfig'))
        else if (data.generation_stage === 'generating_config') addLog(t('log.generatingLLMConfig'))
      }
      if (data.config_generated && data.config) {
        setSimulationConfig(data.config)
        addLog(t('log.configComplete'))
        if (data.summary) {
          addLog(t('log.configSummaryAgents', { count: data.summary.total_agents }))
          addLog(t('log.configSummaryHours', { hours: data.summary.simulation_hours }))
          addLog(t('log.configSummaryPosts', { count: data.summary.initial_posts_count }))
          addLog(t('log.configSummaryTopics', { count: data.summary.hot_topics_count }))
          addLog(
            t('log.configSummaryPlatforms', {
              twitter: data.summary.has_twitter_config ? '✓' : '✗',
              reddit: data.summary.has_reddit_config ? '✓' : '✗',
            }),
          )
        }
        stopConfigPolling()
        setPhase(4)
        addLog(t('log.envSetupComplete'))
        onUpdateStatus('completed')
      }
    } catch (err) {
      console.warn('获取 Config 失败:', err)
    }
  }, [addLog, onUpdateStatus, simulationId, stopConfigPolling, t])

  const startConfigPolling = useCallback(() => {
    if (configTimer.current) return
    addLog(t('log.startGeneratingConfig'))
    configTimer.current = setInterval(fetchConfigRealtime, 2000)
  }, [addLog, fetchConfigRealtime, t])

  const loadPreparedData = useCallback(async () => {
    setPhase(2)
    addLog(t('log.loadingExistingConfig'))
    await fetchProfilesRealtime()
    addLog(t('log.loadedAgentProfiles', { count: profilesRef.current.length }))
    try {
      const res = await getSimulationConfigRealtime(simulationId)
      if (res.success && res.data) {
        if (res.data.config_generated && res.data.config) {
          setSimulationConfig(res.data.config)
          addLog(t('log.configLoadSuccess'))
          if (res.data.summary) {
            addLog(t('log.configSummaryAgents', { count: res.data.summary.total_agents }))
            addLog(t('log.configSummaryHours', { hours: res.data.summary.simulation_hours }))
            addLog(t('log.configSummaryPostsAlt', { count: res.data.summary.initial_posts_count }))
          }
          addLog(t('log.envSetupComplete'))
          setPhase(4)
          onUpdateStatus('completed')
        } else {
          addLog(t('log.configGenerating'))
          startConfigPolling()
        }
      }
    } catch (err) {
      addLog(t('log.loadConfigFailed', { error: (err as Error).message }))
      onUpdateStatus('error')
    }
  }, [addLog, fetchProfilesRealtime, onUpdateStatus, simulationId, startConfigPolling, t])

  const pollPrepareStatus = useCallback(async () => {
    if (!taskIdRef.current && !simulationId) return
    try {
      const res = await getPrepareStatus({
        task_id: taskIdRef.current,
        simulation_id: simulationId,
      })
      if (!res.success || !res.data) return
      const data = res.data
      setPrepareProgress(data.progress || 0)

      if (data.progress_detail) {
        const detail = data.progress_detail
        setCurrentStage(detail.current_stage_name || '')
        const logKey = `${detail.current_stage}-${detail.current_item}-${detail.total_items}`
        if (logKey !== lastMsg.current && detail.item_description) {
          lastMsg.current = logKey
          const stageInfo = `[${detail.stage_index}/${detail.total_stages}]`
          addLog(
            (detail.total_items ?? 0) > 0
              ? `${stageInfo} ${detail.current_stage_name}: ${detail.current_item}/${detail.total_items} - ${detail.item_description}`
              : `${stageInfo} ${detail.current_stage_name}: ${detail.item_description}`,
          )
        }
      } else if (data.message) {
        const match = data.message.match(/\[(\d+)\/(\d+)\]\s*([^:]+)/)
        if (match) setCurrentStage(match[3].trim())
        if (data.message !== lastMsg.current) {
          lastMsg.current = data.message
          addLog(data.message)
        }
      }

      if (data.status === 'completed' || data.status === 'ready' || data.already_prepared) {
        addLog(t('log.prepareComplete'))
        stopPolling()
        stopProfilesPolling()
        await loadPreparedData()
      } else if (data.status === 'failed') {
        addLog(t('log.prepareFailedWithError', { error: data.error || t('common.unknownError') }))
        stopPolling()
        stopProfilesPolling()
      }
    } catch (err) {
      console.warn('轮询状态失败:', err)
    }
  }, [addLog, loadPreparedData, simulationId, stopPolling, stopProfilesPolling, t])

  const startPrepare = useCallback(
    async (force = false) => {
      if (!simulationId) {
        addLog(t('log.errorMissingSimId'))
        onUpdateStatus('error')
        return
      }
      setPhase(1)
      addLog(t('log.simInstanceCreated', { id: simulationId }))
      addLog(t('log.preparingSimEnv'))
      onUpdateStatus('processing')
      try {
        const res = await prepareSimulation({
          simulation_id: simulationId,
          use_llm_for_profiles: true,
          parallel_profile_count: 5,
          force_regenerate: force,
        })
        if (res.success && res.data) {
          if (res.data.already_prepared) {
            addLog(t('log.detectedExistingPrep'))
            await loadPreparedData()
            return
          }
          taskIdRef.current = res.data.task_id ?? null
          setTaskId(res.data.task_id ?? null)
          addLog(t('log.prepareTaskStarted'))
          addLog(t('log.prepareTaskId', { taskId: res.data.task_id }))
          if (res.data.expected_entities_count) {
            expectedRef.current = res.data.expected_entities_count
            setExpectedTotal(res.data.expected_entities_count)
            addLog(t('log.graphEntitiesFound', { count: res.data.expected_entities_count }))
            if (res.data.entity_types?.length) {
              addLog(t('log.entityTypes', { types: res.data.entity_types.join(', ') }))
            }
          }
          addLog(t('log.startPollingProgress'))
          pollTimer.current = setInterval(pollPrepareStatus, 2000)
          profilesTimer.current = setInterval(fetchProfilesRealtime, 3000)
        } else {
          addLog(t('log.prepareFailed', { error: res.error || t('common.unknownError') }))
          onUpdateStatus('error')
        }
      } catch (err) {
        addLog(t('log.prepareException', { error: (err as Error).message }))
        onUpdateStatus('error')
      }
    },
    [
      addLog,
      fetchProfilesRealtime,
      loadPreparedData,
      onUpdateStatus,
      pollPrepareStatus,
      simulationId,
      t,
    ],
  )

  // 阶段切换：进入配置生成阶段时启动配置轮询
  useEffect(() => {
    if (currentStage === '生成Agent人设' || currentStage === 'generating_profiles') {
      setPhase((p) => (p < 1 ? 1 : p))
    } else if (currentStage === '生成模拟配置' || currentStage === 'generating_config') {
      setPhase((p) => (p < 2 ? 2 : p))
      startConfigPolling()
    }
  }, [currentStage, startConfigPolling])

  // 进入/刷新时：先查后端真实状态再决定，避免无脑重新触发 prepare（后端 /prepare 对进行中不去重）。
  const resumeOrStart = useCallback(async () => {
    addLog(t('log.step2Init'))
    if (!simulationId) return

    let state: import('@/lib/api/types').SimulationData | null = null
    try {
      const res = await getSimulation(simulationId)
      if (res.success && res.data) state = res.data
    } catch {
      // 拉状态失败 → 下面回退到首次准备
    }

    const status = state?.status

    // 已准备完成 → 直接加载结果，不触发 prepare
    if (status === 'ready' || state?.config_generated) {
      await loadPreparedData()
      return
    }

    // 准备进行中 → 仅恢复轮询（按 simulationId，不依赖内存 task_id），不重复触发
    if (status === 'preparing') {
      setPhase(1)
      addLog(t('log.resumingPrepare'))
      onUpdateStatus('processing')
      if (state?.entities_count) {
        expectedRef.current = state.entities_count
        setExpectedTotal(state.entities_count)
      }
      await fetchProfilesRealtime()
      pollTimer.current = setInterval(pollPrepareStatus, 2000)
      profilesTimer.current = setInterval(fetchProfilesRealtime, 3000)
      return
    }

    // created / failed / 无记录 → 才（重新）启动准备
    void startPrepare(false)
  }, [
    addLog,
    fetchProfilesRealtime,
    loadPreparedData,
    onUpdateStatus,
    pollPrepareStatus,
    simulationId,
    startPrepare,
    t,
  ])

  // 挂载时恢复或启动（仅一次）
  useEffect(() => {
    if (initedRef.current) return
    initedRef.current = true
    if (simulationId) void resumeOrStart()
    return () => {
      stopPolling()
      stopProfilesPolling()
      stopConfigPolling()
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const handleStart = () => {
    if (useCustomRounds) {
      addLog(t('log.startSimCustomRounds', { rounds: customMaxRounds }))
      onNextStep({ maxRounds: customMaxRounds })
    } else {
      addLog(t('log.startSimAutoRounds', { rounds: autoGeneratedRounds }))
      onNextStep({})
    }
  }

  const done = phase >= 4
  const tc = simulationConfig?.time_config
  const ec = simulationConfig?.event_config

  // 人为本：把 AI 埋下的初始帖子归到各自的「人」名下，作为对其画像的补充。
  // 索引越界 / 负数视为环境帖（system/news），单独成「环境中流传的声音」。
  const postsByAgent = useMemo(() => {
    const m = new Map<number, string[]>()
    for (const p of ec?.initial_posts ?? []) {
      if (!p.content) continue
      const arr = m.get(p.poster_agent_id) ?? []
      arr.push(p.content)
      m.set(p.poster_agent_id, arr)
    }
    return m
  }, [ec])

  const ambientPosts = useMemo(
    () =>
      (ec?.initial_posts ?? []).filter(
        (p) => p.content && (p.poster_agent_id < 0 || p.poster_agent_id >= profiles.length),
      ),
    [ec, profiles.length],
  )

  const selectedIdx = selectedProfile ? profiles.indexOf(selectedProfile) : -1
  const selectedPosts = selectedIdx >= 0 ? (postsByAgent.get(selectedIdx) ?? []) : []

  // 每个「人」的行为画像（活跃时段/发帖频率/影响力…），按 agent_id 归位，供卡片 hover 展示。
  const agentByIndex = useMemo(() => {
    const m = new Map<number, AgentConfig>()
    for (const a of simulationConfig?.agent_configs ?? []) m.set(a.agent_id, a)
    return m
  }, [simulationConfig])

  return (
    <div className="relative flex h-full flex-col overflow-hidden">
      <div className="flex-1 overflow-y-auto px-5 py-10 sm:px-8">
        <div className="mx-auto max-w-2xl">
          {/* 舞台标题 */}
          <div className="animate-rise-in text-center">
            <div className="mx-auto mb-5 flex h-16 w-16 items-center justify-center rounded-2xl bg-gradient-to-br from-indigo-500 to-fuchsia-500 text-white shadow-lg">
              {done ? (
                <CheckCircle2 className="h-8 w-8" />
              ) : (
                <Loader2 className="h-8 w-8 animate-spin" />
              )}
            </div>
            <h2 className="text-2xl font-semibold tracking-tight">
              {done ? t('step2.cGathered') : t('step2.cGathering')}
            </h2>
            <p className="text-muted-foreground mt-2">
              {done
                ? t('step2.cGatheredDone', { count: profiles.length })
                : t('step2.cGatheringSub')}
            </p>
          </div>

          {/* 进展计数 + 软进度 */}
          {!done && (
            <div className="mt-6">
              <p className="text-muted-foreground mb-2 text-center text-sm">
                {t('step2.cGatheredCount', { count: profiles.length, total: expectedTotal ?? '?' })}
              </p>
              <div className="bg-muted h-1.5 overflow-hidden rounded-full">
                <div
                  className="h-full rounded-full bg-gradient-to-r from-indigo-500 to-fuchsia-500 transition-all duration-500"
                  style={{ width: `${Math.max(prepareProgress, 5)}%` }}
                />
              </div>
            </div>
          )}

          {/* 他们生活的世界：叙事方向 + 话题 + 一行概览（为「人」搭好舞台，从属于人） */}
          {simulationConfig && (ec?.narrative_direction || ec?.hot_topics?.length) && (
            <Card variant="glass" className="animate-rise-in mt-6 p-4">
              <p className="text-muted-foreground mb-1.5 flex items-center gap-1.5 text-sm">
                <Compass className="h-4 w-4" />
                {t('step2.cWorld')}
              </p>
              {ec?.narrative_direction && (
                <p className="text-sm leading-relaxed">{ec.narrative_direction}</p>
              )}
              {!!ec?.hot_topics?.length && (
                <div className="mt-3 flex flex-wrap gap-2">
                  {ec.hot_topics.map((topic) => (
                    <SoftBadge key={topic}># {topic}</SoftBadge>
                  ))}
                </div>
              )}
              <p className="text-muted-foreground/80 mt-3 border-t border-white/20 pt-3 text-xs dark:border-white/10">
                {t('step2.cMetaPrefix', {
                  count: profiles.length,
                  hours: tc?.total_simulation_hours ?? '-',
                })}{' '}
                {ec?.hot_topics?.length ? (
                  <TooltipProvider delayDuration={120}>
                    <Tooltip>
                      <TooltipTrigger asChild>
                        <span className="decoration-muted-foreground/40 cursor-help underline underline-offset-2">
                          {t('step2.cMetaTopics', { topics: ec.hot_topics.length })}
                        </span>
                      </TooltipTrigger>
                      <TooltipContent className="bg-popover text-foreground max-w-xs border p-3 shadow-xl backdrop-blur-xl">
                        <div className="flex flex-wrap gap-1.5">
                          {ec.hot_topics.map((topic) => (
                            <SoftBadge key={topic}># {topic}</SoftBadge>
                          ))}
                        </div>
                      </TooltipContent>
                    </Tooltip>
                  </TooltipProvider>
                ) : (
                  t('step2.cMetaTopics', { topics: 0 })
                )}
              </p>
              {!!ambientPosts.length && (
                <div className="mt-3 space-y-2">
                  <p className="text-muted-foreground text-xs">
                    {t('step2.cAmbient', { count: ambientPosts.length })}
                  </p>
                  {ambientPosts.map((post, idx) => (
                    <p
                      key={idx}
                      className="bg-secondary rounded-xl px-3 py-2 text-xs leading-relaxed"
                    >
                      {post.content}
                    </p>
                  ))}
                </div>
              )}
            </Card>
          )}

          {/* 主角：为你召集的人（每个人带上 TA 已发的声音，点开看完整画像） */}
          {profiles.length > 0 && (
            <div className="mt-8">
              <p className="text-muted-foreground mb-3 text-sm font-medium">
                {t('step2.cPeopleWall', { count: profiles.length })}
              </p>
              <TooltipProvider delayDuration={150}>
                <div className="grid gap-3 sm:grid-cols-2">
                  {profiles.map((p, i) => {
                    const myPosts = postsByAgent.get(i) ?? []
                    const topics = p.interested_topics ?? []
                    const behavior = agentByIndex.get(i)
                    const card = (
                      <button
                        type="button"
                        onClick={() => setSelectedProfile(p)}
                        className="glass animate-rise-in flex w-full flex-col rounded-2xl p-4 text-left transition-transform duration-300 hover:-translate-y-0.5"
                      >
                        <div className="flex items-center gap-3">
                          <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-gradient-to-br from-indigo-500 to-fuchsia-500 text-sm font-medium text-white">
                            {(p.name || p.username || '?').slice(0, 1)}
                          </div>
                          <div className="min-w-0 flex-1">
                            <div className="flex items-center gap-1.5">
                              <span className="truncate font-medium">{p.name || p.username}</span>
                              {!!myPosts.length && (
                                <span className="flex shrink-0 items-center gap-0.5 rounded-full bg-indigo-500/15 px-1.5 py-0.5 text-[10px] text-indigo-600 dark:text-indigo-300">
                                  <Megaphone className="h-2.5 w-2.5" />
                                  {t('step2.cVoiced')}
                                </span>
                              )}
                            </div>
                            <div className="text-muted-foreground truncate text-xs">
                              {p.profession || t('step2.unknownProfession')}
                            </div>
                          </div>
                        </div>
                        {p.bio && (
                          <p className="text-muted-foreground mt-2 line-clamp-2 text-xs leading-relaxed">
                            {p.bio}
                          </p>
                        )}
                        {!!topics.length && (
                          <div className="mt-2 flex flex-wrap gap-1.5">
                            {topics.slice(0, 3).map((topic) => (
                              <span
                                key={topic}
                                className="bg-secondary rounded-full px-2 py-0.5 text-[10px]"
                              >
                                {topic}
                              </span>
                            ))}
                            {topics.length > 3 && (
                              <span className="text-muted-foreground px-1 text-[10px]">
                                +{topics.length - 3}
                              </span>
                            )}
                          </div>
                        )}
                        {!!myPosts.length && (
                          <p className="text-foreground/70 mt-3 line-clamp-2 border-l-2 border-indigo-400/50 pl-2 text-xs italic leading-relaxed">
                            “{myPosts[0]}”
                          </p>
                        )}
                      </button>
                    )

                    if (!behavior) return <div key={p.username || i}>{card}</div>
                    return (
                      <Tooltip key={p.username || i}>
                        <TooltipTrigger asChild>{card}</TooltipTrigger>
                        <TooltipContent
                          side="top"
                          className="bg-popover text-foreground w-72 border p-3 shadow-xl backdrop-blur-xl"
                        >
                          <p className="mb-2 text-xs font-medium">
                            {p.name || p.username} · {t('step2.cBehavior')}
                          </p>
                          <PersonaBehavior agent={behavior} />
                        </TooltipContent>
                      </Tooltip>
                    )
                  })}
                </div>
              </TooltipProvider>
            </div>
          )}

          {/* 完成 → 推演时长（轮数）+ 下一步 + 返回 */}
          {done && (
            <div className="animate-rise-in mt-8 flex flex-col items-center gap-4">
              {autoGeneratedRounds != null && (
                <div className="w-full max-w-sm">
                  <p className="text-muted-foreground mb-2 text-center text-xs">
                    {t('step2.cCustomRounds')}
                  </p>
                  <RoundsControl
                    autoGeneratedRounds={autoGeneratedRounds}
                    useCustomRounds={useCustomRounds}
                    setUseCustomRounds={setUseCustomRounds}
                    customMaxRounds={customMaxRounds}
                    setCustomMaxRounds={setCustomMaxRounds}
                  />
                </div>
              )}
              <Button
                variant="gradient"
                className="h-12 gap-2 rounded-full px-8 text-base"
                onClick={handleStart}
              >
                <Sparkles className="h-5 w-5" />
                {t('step2.cNext')}
                <ArrowRight className="h-5 w-5" />
              </Button>
              <button
                type="button"
                onClick={onGoBack}
                className="text-muted-foreground hover:text-foreground inline-flex items-center gap-1 text-xs transition-colors"
              >
                <ArrowLeft className="h-3.5 w-3.5" />
                {t('step2.cBack')}
              </button>
            </div>
          )}

          {/* 幕后：实例信息 / 环境参数 / 激活事件 / 重新召集 / 原始日志 */}
          <div className="mt-10">
            <CollapsibleHeader
              open={backstageOpen}
              onToggle={() => setBackstageOpen((o) => !o)}
              icon={<Code className="h-4 w-4" />}
              label={t('step2.cBackstage')}
              hint={t('step2.cBackstageHint')}
            />

            {backstageOpen && (
              <div className="mt-3 space-y-4">
                {/* 完整工程流水线 01→05；内容已在上方舞台展示的步骤只保留状态卡，不重复 */}
                {/* 01 实例初始化（工程 ID，舞台未展示，完整保留） */}
                <SimInstanceCard
                  phase={phase}
                  projectData={projectData}
                  simulationId={simulationId}
                  taskId={taskId}
                />

                {/* 02 生成人设（人物墙已在舞台展示，这里只留状态） */}
                <StepCard
                  num="02"
                  title={t('step2.generateAgentPersona')}
                  status={phase > 1 ? 'completed' : phase === 1 ? 'processing' : 'pending'}
                  statusText={
                    phase > 1
                      ? t('common.completed')
                      : phase === 1
                        ? t('step2.generating')
                        : t('common.pending')
                  }
                  apiNote="POST /api/simulation/prepare"
                  description={t('step2.generateAgentPersonaDesc')}
                >
                  <p className="text-muted-foreground text-xs">{t('step2.cSeeStage')}</p>
                </StepCard>

                {/* 03 平台配置（时间/算法/LLM，舞台未展示，完整保留） */}
                <PlatformConfigCard phase={phase} config={simulationConfig} />

                {/* 04 初始激活（叙事/话题已在舞台；这里保留工程视角的「初始化序列」——按播种顺序的帖子时间线） */}
                <StepCard
                  num="04"
                  title={t('step2.initialActivation')}
                  status={phase > 3 ? 'completed' : phase === 3 ? 'processing' : 'pending'}
                  statusText={
                    phase > 3
                      ? t('common.completed')
                      : phase === 3
                        ? t('step2.orchestrating')
                        : t('common.pending')
                  }
                  apiNote="POST /api/simulation/prepare"
                  description={t('step2.initialActivationDesc')}
                >
                  {ec?.initial_posts?.length ? (
                    <div>
                      <span className="text-muted-foreground mb-2 block text-[10px] font-semibold">
                        {t('step2.initialActivationSeq', { count: ec.initial_posts.length })}
                      </span>
                      <div className="border-muted space-y-2 border-l-2 pl-4">
                        {ec.initial_posts.map((post, idx) => {
                          const author = profiles[post.poster_agent_id]
                          return (
                            <div key={idx} className="relative">
                              <span className="bg-brand absolute -left-[21px] top-1.5 h-2 w-2 rounded-full" />
                              <div className="bg-muted/50 rounded-md p-2.5">
                                <div className="text-muted-foreground mb-1 flex items-center gap-2 text-[10px]">
                                  {post.poster_type && (
                                    <span className="font-semibold">{post.poster_type}</span>
                                  )}
                                  <span className="font-mono">#{idx + 1}</span>
                                  <span>
                                    @{author?.username || `agent_${post.poster_agent_id}`}
                                  </span>
                                </div>
                                <p className="text-[11px] leading-relaxed">{post.content}</p>
                              </div>
                            </div>
                          )
                        })}
                      </div>
                    </div>
                  ) : (
                    <p className="text-muted-foreground text-xs">{t('step2.cSeeStage')}</p>
                  )}
                </StepCard>

                {/* 05 准备完成（轮数/开始已是舞台主操作，这里只留状态 + 重新召集） */}
                <StepCard
                  num="05"
                  title={t('step2.setupComplete')}
                  status={phase >= 4 ? 'processing' : 'pending'}
                  statusText={phase >= 4 ? t('step1.inProgress') : t('common.pending')}
                  apiNote="POST /api/simulation/start"
                  description={t('step2.setupCompleteDesc')}
                >
                  <p className="text-muted-foreground mb-3 text-xs">{t('step2.cSeeStage')}</p>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => startPrepare(true)}
                    className="gap-1.5"
                  >
                    <RefreshCw className="h-3.5 w-3.5" />
                    {t('step2.cRegenerate')}
                  </Button>
                </StepCard>

                <SystemLogTerminal logs={systemLogs} badge={simulationId || 'NO_SIMULATION'} />
              </div>
            )}
          </div>
        </div>
      </div>

      <ProfileModal
        profile={selectedProfile}
        posts={selectedPosts}
        onClose={() => setSelectedProfile(null)}
      />
    </div>
  )
}
