import { useMemo, useState } from 'react'
import { useTranslation } from 'react-i18next'

import { Code, Sparkles, ArrowRight, ArrowLeft, RefreshCw, Compass, Megaphone } from 'lucide-react'

import { SystemLogTerminal } from '@/components/SystemLogTerminal'
import { StepCard } from '@/components/StepCard'
import { SimInstanceCard } from '@/components/step2/SimInstanceCard'
import { PlatformConfigCard } from '@/components/step2/PlatformConfigCard'
import { ProfileModal } from '@/components/step2/ProfileModal'
import { PersonaBehavior } from '@/components/step2/PersonaBehavior'
import { RoundsControl } from '@/components/step2/RoundsControl'
import { useStep2Orchestration } from '@/components/step2/useStep2Orchestration'
import { StageIcon } from '@/components/common/StageIcon'
import { SoftProgress } from '@/components/common/SoftProgress'
import { Button } from '@/components/ui/button'
import { TextButton } from '@/components/ui/text-button'
import { Card } from '@/components/ui/card'
import { CollapsibleHeader } from '@/components/ui/collapsible-header'
import { SelectableCard } from '@/components/ui/selectable-card'
import { SoftBadge } from '@/components/ui/soft-badge'
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import type { ProjectData, SystemLog } from '@/lib/process-types'
import type { AgentConfig, Profile } from '@/lib/step2-types'
import type { SimulationQuota } from '@/lib/api/simulation'
import type { WorkflowStatus } from '@/components/WorkflowLayout'

interface Step2Props {
  simulationId: string
  projectData: ProjectData | null
  systemLogs: SystemLog[]
  addLog: (msg: string) => void
  onUpdateStatus: (status: WorkflowStatus) => void
  onGoBack: () => void
  onNextStep: (params: { maxRounds?: number }) => void
  /** 并发名额快照（顶栏展示用） */
  quota?: SimulationQuota | null
  /** 点击进入推演时做权威的实时校验，返回最新名额 */
  refreshQuota?: () => Promise<SimulationQuota | null>
}

/** 步骤二：环境搭建编排器（准备/人设/配置 三路轮询 + 五张卡片）。 */
export function Step2EnvSetup({
  simulationId,
  projectData,
  systemLogs,
  addLog,
  onUpdateStatus,
  onGoBack,
  onNextStep,
  quota,
  refreshQuota,
}: Step2Props) {
  const { t } = useTranslation()

  // 三路轮询 + 恢复/启动状态机收拢在编排 hook 内；本组件只消费状态做渲染。
  const {
    phase,
    taskId,
    prepareProgress,
    profiles,
    expectedTotal,
    simulationConfig,
    startPrepare,
  } = useStep2Orchestration({ simulationId, addLog, onUpdateStatus, kind: projectData?.kind })

  // 纯视图态（不属于编排逻辑）
  const [selectedProfile, setSelectedProfile] = useState<Profile | null>(null)
  const [useCustomRounds, setUseCustomRounds] = useState(false)
  const [customMaxRounds, setCustomMaxRounds] = useState(40)
  const [backstageOpen, setBackstageOpen] = useState(false)
  const [quotaFull, setQuotaFull] = useState<SimulationQuota | null>(null) // 非空 → 显示名额已满弹框
  const [checkingQuota, setCheckingQuota] = useState(false)

  // 从配置推算自动轮数（不小于 40）
  const autoGeneratedRounds = useMemo(() => {
    const tc = simulationConfig?.time_config
    if (!tc?.total_simulation_hours || !tc?.minutes_per_round) return null
    return Math.max(Math.floor((tc.total_simulation_hours * 60) / tc.minutes_per_round), 40)
  }, [simulationConfig])

  const proceed = () => {
    if (useCustomRounds) {
      addLog(t('log.startSimCustomRounds', { rounds: customMaxRounds }))
      onNextStep({ maxRounds: customMaxRounds })
    } else {
      addLog(t('log.startSimAutoRounds', { rounds: autoGeneratedRounds }))
      onNextStep({})
    }
  }

  // 进入推演前先做权威的实时名额校验：已满则弹框拦截、不进入下一步；拉取失败则放行（后端兜底）。
  const handleStart = async () => {
    if (checkingQuota) return
    setCheckingQuota(true)
    try {
      const fresh = refreshQuota ? await refreshQuota() : null
      if (fresh && fresh.running >= fresh.limit) {
        setQuotaFull(fresh)
        return
      }
      proceed()
    } finally {
      setCheckingQuota(false)
    }
  }

  const done = phase >= 4
  const tc = simulationConfig?.time_config
  const ec = simulationConfig?.event_config

  // 人为本：把 AI 埋下的初始帖子归到各自的「人」名下，作为对其画像的补充。
  // 索引越界 / 负数视为环境帖（system/news），单独成「环境中流传的声音」。
  const postsByAgent = useMemo(() => {
    const m = new Map<number, string[]>()
    for (const p of ec?.initial_posts ?? []) {
      if (!p.content) continue
      const arr = m.get(p.poster_agent_id) ?? []
      arr.push(p.content)
      m.set(p.poster_agent_id, arr)
    }
    return m
  }, [ec])

  const ambientPosts = useMemo(
    () =>
      (ec?.initial_posts ?? []).filter(
        (p) => p.content && (p.poster_agent_id < 0 || p.poster_agent_id >= profiles.length),
      ),
    [ec, profiles.length],
  )

  const selectedIdx = selectedProfile ? profiles.indexOf(selectedProfile) : -1
  const selectedPosts = selectedIdx >= 0 ? (postsByAgent.get(selectedIdx) ?? []) : []

  // 每个「人」的行为画像（活跃时段/发帖频率/影响力…），按 agent_id 归位，供卡片 hover 展示。
  const agentByIndex = useMemo(() => {
    const m = new Map<number, AgentConfig>()
    for (const a of simulationConfig?.agent_configs ?? []) m.set(a.agent_id, a)
    return m
  }, [simulationConfig])

  return (
    <div className="relative flex h-full flex-col overflow-hidden">
      <div className="flex-1 overflow-y-auto px-5 py-10 sm:px-8">
        <div className="mx-auto max-w-2xl">
          {/* 舞台标题 */}
          <div className="animate-rise-in text-center">
            <StageIcon done={done} />
            <h2 className="text-2xl font-semibold tracking-tight">
              {done ? t('step2.cGathered') : t('step2.cGathering')}
            </h2>
            <p className="text-muted-foreground mt-2">
              {done
                ? t('step2.cGatheredDone', { count: profiles.length })
                : t('step2.cGatheringSub')}
            </p>
          </div>

          {/* 进展计数 + 软进度 */}
          {!done && (
            <div className="mt-6">
              <p className="text-muted-foreground mb-2 text-center text-sm">
                {t('step2.cGatheredCount', { count: profiles.length, total: expectedTotal ?? '?' })}
              </p>
              <SoftProgress value={prepareProgress} floor={5} />
            </div>
          )}

          {/* 他们生活的世界：叙事方向 + 话题 + 一行概览（为「人」搭好舞台，从属于人） */}
          {simulationConfig && (ec?.narrative_direction || ec?.hot_topics?.length) && (
            <Card variant="glass" className="animate-rise-in mt-6 p-4">
              <p className="text-muted-foreground mb-1.5 flex items-center gap-1.5 text-sm">
                <Compass className="h-4 w-4" />
                {t('step2.cWorld')}
              </p>
              {ec?.narrative_direction && (
                <p className="text-sm leading-relaxed">{ec.narrative_direction}</p>
              )}
              {!!ec?.hot_topics?.length && (
                <div className="mt-3 flex flex-wrap gap-2">
                  {ec.hot_topics.map((topic) => (
                    <SoftBadge key={topic}># {topic}</SoftBadge>
                  ))}
                </div>
              )}
              <p className="text-muted-foreground/80 mt-3 border-t border-white/20 pt-3 text-xs dark:border-white/10">
                {t('step2.cMetaPrefix', {
                  count: profiles.length,
                  hours: tc?.total_simulation_hours ?? '-',
                })}{' '}
                {ec?.hot_topics?.length ? (
                  <TooltipProvider delayDuration={120}>
                    <Tooltip>
                      <TooltipTrigger asChild>
                        <span className="decoration-muted-foreground/40 cursor-help underline underline-offset-2">
                          {t('step2.cMetaTopics', { topics: ec.hot_topics.length })}
                        </span>
                      </TooltipTrigger>
                      <TooltipContent className="bg-popover text-foreground max-w-xs border p-3 shadow-xl backdrop-blur-xl">
                        <div className="flex flex-wrap gap-1.5">
                          {ec.hot_topics.map((topic) => (
                            <SoftBadge key={topic}># {topic}</SoftBadge>
                          ))}
                        </div>
                      </TooltipContent>
                    </Tooltip>
                  </TooltipProvider>
                ) : (
                  t('step2.cMetaTopics', { topics: 0 })
                )}
              </p>
              {!!ambientPosts.length && (
                <div className="mt-3 space-y-2">
                  <p className="text-muted-foreground text-xs">
                    {t('step2.cAmbient', { count: ambientPosts.length })}
                  </p>
                  {ambientPosts.map((post, idx) => (
                    <p
                      key={idx}
                      className="bg-secondary rounded-xl px-3 py-2 text-xs leading-relaxed"
                    >
                      {post.content}
                    </p>
                  ))}
                </div>
              )}
            </Card>
          )}

          {/* 主角：为你召集的人（每个人带上 TA 已发的声音，点开看完整画像） */}
          {profiles.length > 0 && (
            <div className="mt-8">
              <p className="text-muted-foreground mb-3 text-sm font-medium">
                {t('step2.cPeopleWall', { count: profiles.length })}
              </p>
              <TooltipProvider delayDuration={150}>
                <div className="grid gap-3 sm:grid-cols-2">
                  {profiles.map((p, i) => {
                    const myPosts = postsByAgent.get(i) ?? []
                    const topics = p.interested_topics ?? []
                    const behavior = agentByIndex.get(i)
                    const card = (
                      <SelectableCard
                        surface="glass"
                        onClick={() => setSelectedProfile(p)}
                        className="animate-rise-in flex w-full flex-col rounded-2xl p-4"
                      >
                        <div className="flex items-center gap-3">
                          <div className="bg-brand-gradient flex h-10 w-10 shrink-0 items-center justify-center rounded-full text-sm font-medium text-white">
                            {(p.name || p.username || '?').slice(0, 1)}
                          </div>
                          <div className="min-w-0 flex-1">
                            <div className="flex items-center gap-1.5">
                              <span className="truncate font-medium">{p.name || p.username}</span>
                              {!!myPosts.length && (
                                <span className="flex shrink-0 items-center gap-0.5 rounded-full bg-indigo-500/15 px-1.5 py-0.5 text-[10px] text-indigo-600 dark:text-indigo-300">
                                  <Megaphone className="h-2.5 w-2.5" />
                                  {t('step2.cVoiced')}
                                </span>
                              )}
                            </div>
                            <div className="text-muted-foreground truncate text-xs">
                              {p.profession || t('step2.unknownProfession')}
                            </div>
                          </div>
                        </div>
                        {p.bio && (
                          <p className="text-muted-foreground mt-2 line-clamp-2 text-xs leading-relaxed">
                            {p.bio}
                          </p>
                        )}
                        {!!topics.length && (
                          <div className="mt-2 flex flex-wrap gap-1.5">
                            {topics.slice(0, 3).map((topic) => (
                              <SoftBadge key={topic} className="px-2 text-[10px]">
                                {topic}
                              </SoftBadge>
                            ))}
                            {topics.length > 3 && (
                              <span className="text-muted-foreground px-1 text-[10px]">
                                +{topics.length - 3}
                              </span>
                            )}
                          </div>
                        )}
                        {!!myPosts.length && (
                          <p className="text-foreground/70 mt-3 line-clamp-2 border-l-2 border-indigo-400/50 pl-2 text-xs italic leading-relaxed">
                            “{myPosts[0]}”
                          </p>
                        )}
                      </SelectableCard>
                    )

                    if (!behavior) return <div key={p.username || i}>{card}</div>
                    return (
                      <Tooltip key={p.username || i}>
                        <TooltipTrigger asChild>{card}</TooltipTrigger>
                        <TooltipContent
                          side="top"
                          className="bg-popover text-foreground w-72 border p-3 shadow-xl backdrop-blur-xl"
                        >
                          <p className="mb-2 text-xs font-medium">
                            {p.name || p.username} · {t('step2.cBehavior')}
                          </p>
                          <PersonaBehavior agent={behavior} />
                        </TooltipContent>
                      </Tooltip>
                    )
                  })}
                </div>
              </TooltipProvider>
            </div>
          )}

          {/* 完成 → 推演时长（轮数）+ 下一步 + 返回 */}
          {done && (
            <div className="animate-rise-in mt-8 flex flex-col items-center gap-4">
              {autoGeneratedRounds != null && (
                <div className="w-full max-w-sm">
                  <p className="text-muted-foreground mb-2 text-center text-xs">
                    {t('step2.cCustomRounds')}
                  </p>
                  <RoundsControl
                    autoGeneratedRounds={autoGeneratedRounds}
                    useCustomRounds={useCustomRounds}
                    setUseCustomRounds={setUseCustomRounds}
                    customMaxRounds={customMaxRounds}
                    setCustomMaxRounds={setCustomMaxRounds}
                  />
                </div>
              )}
              <Button
                variant="gradient"
                className="h-12 gap-2 rounded-full px-8 text-base"
                onClick={() => void handleStart()}
                disabled={checkingQuota}
              >
                <Sparkles className="h-5 w-5" />
                {t('step2.cNext')}
                <ArrowRight className="h-5 w-5" />
              </Button>
              {quota && (
                <p className="text-muted-foreground -mt-1 text-xs">
                  {t('main.quotaChip', { running: quota.running, limit: quota.limit })}
                </p>
              )}
              <TextButton onClick={onGoBack} className="inline-flex items-center gap-1 text-xs">
                <ArrowLeft className="h-3.5 w-3.5" />
                {t('step2.cBack')}
              </TextButton>
            </div>
          )}

          {/* 幕后：实例信息 / 环境参数 / 激活事件 / 重新召集 / 原始日志 */}
          <div className="mt-10">
            <CollapsibleHeader
              open={backstageOpen}
              onToggle={() => setBackstageOpen((o) => !o)}
              icon={<Code className="h-4 w-4" />}
              label={t('step2.cBackstage')}
              hint={t('step2.cBackstageHint')}
            />

            {backstageOpen && (
              <div className="mt-3 space-y-4">
                {/* 完整工程流水线 01→05；内容已在上方舞台展示的步骤只保留状态卡，不重复 */}
                {/* 01 实例初始化（工程 ID，舞台未展示，完整保留） */}
                <SimInstanceCard
                  phase={phase}
                  projectData={projectData}
                  simulationId={simulationId}
                  taskId={taskId}
                />

                {/* 02 生成人设（人物墙已在舞台展示，这里只留状态） */}
                <StepCard
                  num="02"
                  title={t('step2.generateAgentPersona')}
                  status={phase > 1 ? 'completed' : phase === 1 ? 'processing' : 'pending'}
                  statusText={
                    phase > 1
                      ? t('common.completed')
                      : phase === 1
                        ? t('step2.generating')
                        : t('common.pending')
                  }
                  apiNote="POST /api/simulation/prepare"
                  description={t('step2.generateAgentPersonaDesc')}
                >
                  <p className="text-muted-foreground text-xs">{t('step2.cSeeStage')}</p>
                </StepCard>

                {/* 03 平台配置（时间/算法/LLM，舞台未展示，完整保留） */}
                <PlatformConfigCard phase={phase} config={simulationConfig} />

                {/* 04 初始激活（叙事/话题已在舞台；这里保留工程视角的「初始化序列」——按播种顺序的帖子时间线） */}
                <StepCard
                  num="04"
                  title={t('step2.initialActivation')}
                  status={phase > 3 ? 'completed' : phase === 3 ? 'processing' : 'pending'}
                  statusText={
                    phase > 3
                      ? t('common.completed')
                      : phase === 3
                        ? t('step2.orchestrating')
                        : t('common.pending')
                  }
                  apiNote="POST /api/simulation/prepare"
                  description={t('step2.initialActivationDesc')}
                >
                  {ec?.initial_posts?.length ? (
                    <div>
                      <span className="text-muted-foreground mb-2 block text-[10px] font-semibold">
                        {t('step2.initialActivationSeq', { count: ec.initial_posts.length })}
                      </span>
                      <div className="border-muted space-y-2 border-l-2 pl-4">
                        {ec.initial_posts.map((post, idx) => {
                          const author = profiles[post.poster_agent_id]
                          return (
                            <div key={idx} className="relative">
                              <span className="bg-brand absolute -left-[21px] top-1.5 h-2 w-2 rounded-full" />
                              <div className="bg-muted/50 rounded-md p-2.5">
                                <div className="text-muted-foreground mb-1 flex items-center gap-2 text-[10px]">
                                  {post.poster_type && (
                                    <span className="font-semibold">{post.poster_type}</span>
                                  )}
                                  <span className="font-mono">#{idx + 1}</span>
                                  <span>
                                    @{author?.username || `agent_${post.poster_agent_id}`}
                                  </span>
                                </div>
                                <p className="text-[11px] leading-relaxed">{post.content}</p>
                              </div>
                            </div>
                          )
                        })}
                      </div>
                    </div>
                  ) : (
                    <p className="text-muted-foreground text-xs">{t('step2.cSeeStage')}</p>
                  )}
                </StepCard>

                {/* 05 准备完成（轮数/开始已是舞台主操作，这里只留状态 + 重新召集） */}
                <StepCard
                  num="05"
                  title={t('step2.setupComplete')}
                  status={phase >= 4 ? 'processing' : 'pending'}
                  statusText={phase >= 4 ? t('step1.inProgress') : t('common.pending')}
                  apiNote="POST /api/simulation/start"
                  description={t('step2.setupCompleteDesc')}
                >
                  <p className="text-muted-foreground mb-3 text-xs">{t('step2.cSeeStage')}</p>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => startPrepare(true)}
                    className="gap-1.5"
                  >
                    <RefreshCw className="h-3.5 w-3.5" />
                    {t('step2.cRegenerate')}
                  </Button>
                </StepCard>

                <SystemLogTerminal logs={systemLogs} badge={simulationId || 'NO_SIMULATION'} />
              </div>
            )}
          </div>
        </div>
      </div>

      <ProfileModal
        profile={selectedProfile}
        posts={selectedPosts}
        onClose={() => setSelectedProfile(null)}
      />

      {/* 名额已满：拦截进入推演，说清原因与下一步该怎么办 */}
      <Dialog open={!!quotaFull} onOpenChange={(o) => !o && setQuotaFull(null)}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>{t('step2.quotaFullTitle')}</DialogTitle>
            <DialogDescription className="leading-relaxed">
              {t('step2.quotaFullBody', {
                running: quotaFull?.running ?? 0,
                limit: quotaFull?.limit ?? 0,
              })}
            </DialogDescription>
          </DialogHeader>
          <div className="mt-4 flex justify-end">
            <Button variant="outline" onClick={() => setQuotaFull(null)}>
              {t('step2.quotaFullOk')}
            </Button>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  )
}
