import { useTranslation } from 'react-i18next'
import { Clock } from 'lucide-react'

import { Card } from '@/components/ui/card'
import { Checkbox } from '@/components/ui/checkbox'
import { Label } from '@/components/ui/label'
import { Slider } from '@/components/ui/slider'
import { cn } from '@/lib/utils'

const RECOMMENDED_ROUNDS = 40

interface Props {
  autoGeneratedRounds: number
  useCustomRounds: boolean
  setUseCustomRounds: (v: boolean) => void
  customMaxRounds: number
  setCustomMaxRounds: (v: number) => void
}

/**
 * 推演时长（轮数）控件：默认走自动估算 + 预计耗时；
 * 勾选自定义后出现滑块（含推荐 40 轮指示，新手首跑减轮避坑）。
 */
export function RoundsControl({
  autoGeneratedRounds,
  useCustomRounds,
  setUseCustomRounds,
  customMaxRounds,
  setCustomMaxRounds,
}: Props) {
  const { t } = useTranslation()
  const rounds = useCustomRounds ? customMaxRounds : autoGeneratedRounds

  return (
    <Card variant="glass" className="w-full p-4 text-left">
      <div className="flex items-center justify-between gap-3">
        <div className="flex min-w-0 flex-wrap items-baseline gap-x-2 gap-y-0.5">
          <span className="text-2xl font-semibold">{rounds}</span>
          <span className="text-muted-foreground text-xs">{t('step2.roundsUnit')}</span>
          <span className="text-muted-foreground flex items-center gap-1 text-xs">
            <Clock className="h-3 w-3" />
            {t('step2.estimatedDuration', { minutes: Math.round(rounds * 0.6) })}
          </span>
        </div>
        <Label className="text-muted-foreground flex shrink-0 cursor-pointer items-center gap-2 whitespace-nowrap text-xs">
          <Checkbox
            checked={useCustomRounds}
            onCheckedChange={(c) => setUseCustomRounds(c === true)}
          />
          {t('step2.customToggle')}
        </Label>
      </div>

      {useCustomRounds ? (
        <CustomRoundsSlider
          autoGeneratedRounds={autoGeneratedRounds}
          customMaxRounds={customMaxRounds}
          setCustomMaxRounds={setCustomMaxRounds}
        />
      ) : (
        <button
          type="button"
          onClick={() => setUseCustomRounds(true)}
          className="text-muted-foreground hover:text-foreground mt-2 text-left text-[11px] transition-colors"
        >
          {t('step2.customTip')} ➝
        </button>
      )}
    </Card>
  )
}

/** 自定义轮数滑块：10~自动估算之间，含可点击的推荐值指示线。 */
function CustomRoundsSlider({
  autoGeneratedRounds,
  customMaxRounds,
  setCustomMaxRounds,
}: {
  autoGeneratedRounds: number
  customMaxRounds: number
  setCustomMaxRounds: (v: number) => void
}) {
  const { t } = useTranslation()
  const min = 10
  const max = autoGeneratedRounds
  const recommendInRange = RECOMMENDED_ROUNDS >= min && RECOMMENDED_ROUNDS <= max
  const recommendPercent = max > min ? ((RECOMMENDED_ROUNDS - min) / (max - min)) * 100 : 0
  const atRecommended = customMaxRounds === RECOMMENDED_ROUNDS

  return (
    <div className="mt-4">
      <div className="relative">
        <Slider
          min={min}
          max={max}
          step={5}
          value={[customMaxRounds]}
          onValueChange={(v) => setCustomMaxRounds(v[0])}
        />
        {recommendInRange && (
          <span
            className={cn(
              'pointer-events-none absolute top-1/2 h-3 w-px -translate-x-1/2 -translate-y-1/2',
              atRecommended ? 'bg-indigo-500' : 'bg-foreground/30',
            )}
            style={{ left: `${recommendPercent}%` }}
          />
        )}
      </div>

      <div className="text-muted-foreground relative mt-1 flex justify-between text-[10px]">
        <span>{min}</span>
        {recommendInRange && (
          <button
            type="button"
            onClick={() => setCustomMaxRounds(RECOMMENDED_ROUNDS)}
            className={cn(
              'hover:text-foreground absolute -translate-x-1/2 whitespace-nowrap transition-colors',
              atRecommended && 'font-semibold text-indigo-500',
            )}
            style={{ left: `${recommendPercent}%` }}
          >
            {t('step2.recommendedRounds', { rounds: RECOMMENDED_ROUNDS })}
          </button>
        )}
        <span>{max}</span>
      </div>
    </div>
  )
}
