import { useTranslation } from 'react-i18next'
import { Clock, RefreshCw } from 'lucide-react'

import { StepCard } from '@/components/StepCard'
import { Button } from '@/components/ui/button'
import { Checkbox } from '@/components/ui/checkbox'
import { Label } from '@/components/ui/label'
import { Slider } from '@/components/ui/slider'
import { cn } from '@/lib/utils'

interface Props {
  phase: number
  hasConfig: boolean
  autoGeneratedRounds: number | null
  useCustomRounds: boolean
  setUseCustomRounds: (v: boolean) => void
  customMaxRounds: number
  setCustomMaxRounds: (v: number) => void
  onBack: () => void
  onStart: () => void
  /** 重新生成环境（人设/配置，force_regenerate） */
  onRegenerate?: () => void
}

/** 步骤 05：准备完成（模拟轮数配置 + 开始/返回）。 */
export function SetupCompleteCard({
  phase,
  hasConfig,
  autoGeneratedRounds,
  useCustomRounds,
  setUseCustomRounds,
  customMaxRounds,
  setCustomMaxRounds,
  onBack,
  onStart,
  onRegenerate,
}: Props) {
  const { t } = useTranslation()

  return (
    <StepCard
      num="05"
      title={t('step2.setupComplete')}
      status={phase >= 4 ? 'processing' : 'pending'}
      statusText={phase >= 4 ? t('step1.inProgress') : t('common.pending')}
      active={phase === 4}
      apiNote="POST /api/simulation/start"
      description={t('step2.setupCompleteDesc')}
    >
      {hasConfig && autoGeneratedRounds && (
        <div className="mb-4 rounded-md border p-4">
          <div className="mb-3 flex items-start justify-between gap-2">
            <div>
              <span className="block text-xs font-semibold">{t('step2.roundsConfig')}</span>
            </div>
            <Label className="flex cursor-pointer items-center gap-2 text-xs">
              <Checkbox
                checked={useCustomRounds}
                onCheckedChange={(c) => setUseCustomRounds(c === true)}
              />
              {t('step2.customToggle')}
            </Label>
          </div>

          {useCustomRounds ? (
            <CustomRoundsSlider
              autoGeneratedRounds={autoGeneratedRounds}
              customMaxRounds={customMaxRounds}
              setCustomMaxRounds={setCustomMaxRounds}
            />
          ) : (
            <div className="flex items-center gap-4">
              <div className="flex items-baseline gap-1">
                <span className="font-mono text-2xl font-bold">{autoGeneratedRounds}</span>
                <span className="text-muted-foreground text-xs">{t('step2.roundsUnit')}</span>
              </div>
              <span className="bg-muted flex items-center gap-1 rounded px-2 py-1 text-[10px]">
                <Clock className="h-3 w-3" />
                {t('step2.estimatedDurationFull', {
                  minutes: Math.round(autoGeneratedRounds * 0.6),
                })}
              </span>
              <button
                onClick={() => setUseCustomRounds(true)}
                className="text-brand ml-auto text-[11px] hover:underline"
              >
                {t('step2.customTip')} ➝
              </button>
            </div>
          )}
        </div>
      )}

      <div className="flex gap-3">
        <Button variant="outline" className="flex-1" onClick={onBack}>
          ← {t('step2.backToGraphBuild')}
        </Button>
        <Button className="flex-1" disabled={phase < 4} onClick={onStart}>
          {t('step2.startDualWorldSim')} ➝
        </Button>
      </div>

      {phase >= 4 && onRegenerate && (
        <Button
          variant="ghost"
          size="sm"
          onClick={onRegenerate}
          className="text-muted-foreground hover:text-foreground mt-2 w-full gap-1.5"
          title={t('step2.regenerateEnvHint')}
        >
          <RefreshCw className="h-3.5 w-3.5" />
          {t('step2.regenerateEnv')}
        </Button>
      )}
    </StepCard>
  )
}

const RECOMMENDED_ROUNDS = 40

/** 自定义轮数滑块：实时填充背景 + 可点击的推荐值指示线。 */
function CustomRoundsSlider({
  autoGeneratedRounds,
  customMaxRounds,
  setCustomMaxRounds,
}: {
  autoGeneratedRounds: number
  customMaxRounds: number
  setCustomMaxRounds: (v: number) => void
}) {
  const { t } = useTranslation()
  const min = 10
  const max = autoGeneratedRounds
  // 推荐值在轨道上的百分比位置（夹在范围内，避免溢出）。
  const recommendInRange = RECOMMENDED_ROUNDS >= min && RECOMMENDED_ROUNDS <= max
  const recommendPercent = max > min ? ((RECOMMENDED_ROUNDS - min) / (max - min)) * 100 : 0
  const atRecommended = customMaxRounds === RECOMMENDED_ROUNDS

  return (
    <div>
      <div className="mb-2 flex items-baseline gap-2">
        <span className="font-mono text-2xl font-bold">{customMaxRounds}</span>
        <span className="text-muted-foreground text-xs">{t('step2.roundsUnit')}</span>
        <span className="text-muted-foreground ml-auto text-[11px]">
          {t('step2.estimatedDuration', { minutes: Math.round(customMaxRounds * 0.6) })}
        </span>
      </div>

      <div className="relative">
        <Slider
          min={min}
          max={max}
          step={5}
          value={[customMaxRounds]}
          onValueChange={(v) => setCustomMaxRounds(v[0])}
        />
        {/* 推荐值指示线（叠加在轨道上） */}
        {recommendInRange && (
          <span
            className={cn(
              'pointer-events-none absolute top-1/2 h-3 w-px -translate-x-1/2 -translate-y-1/2',
              atRecommended ? 'bg-brand' : 'bg-foreground/30',
            )}
            style={{ left: `${recommendPercent}%` }}
          />
        )}
      </div>

      <div className="text-muted-foreground relative mt-1 flex justify-between text-[10px]">
        <span>{min}</span>
        {recommendInRange && (
          <button
            type="button"
            onClick={() => setCustomMaxRounds(RECOMMENDED_ROUNDS)}
            className={cn(
              'hover:text-foreground absolute -translate-x-1/2 whitespace-nowrap transition-colors',
              atRecommended && 'text-brand font-semibold',
            )}
            style={{ left: `${recommendPercent}%` }}
          >
            {t('step2.recommendedRounds', { rounds: RECOMMENDED_ROUNDS })}
          </button>
        )}
        <span>{max}</span>
      </div>
    </div>
  )
}
