import { useTranslation } from 'react-i18next'
import { Clock } from 'lucide-react'

import { StepCard } from './StepCard'

interface Props {
  phase: number
  hasConfig: boolean
  autoGeneratedRounds: number | null
  useCustomRounds: boolean
  setUseCustomRounds: (v: boolean) => void
  customMaxRounds: number
  setCustomMaxRounds: (v: number) => void
  onBack: () => void
  onStart: () => void
}

/** 步骤 05：准备完成（模拟轮数配置 + 开始/返回）。 */
export function SetupCompleteCard({
  phase,
  hasConfig,
  autoGeneratedRounds,
  useCustomRounds,
  setUseCustomRounds,
  customMaxRounds,
  setCustomMaxRounds,
  onBack,
  onStart,
}: Props) {
  const { t } = useTranslation()

  return (
    <StepCard
      num="05"
      title={t('step2.setupComplete')}
      status={phase >= 4 ? 'processing' : 'pending'}
      statusText={phase >= 4 ? t('step1.inProgress') : t('common.pending')}
      active={phase === 4}
      apiNote="POST /api/simulation/start"
      description={t('step2.setupCompleteDesc')}
    >
      {hasConfig && autoGeneratedRounds && (
        <div className="mb-4 rounded-md border p-4">
          <div className="mb-3 flex items-start justify-between gap-2">
            <div>
              <span className="block text-xs font-semibold">{t('step2.roundsConfig')}</span>
            </div>
            <label className="flex cursor-pointer items-center gap-2 text-xs">
              <input
                type="checkbox"
                checked={useCustomRounds}
                onChange={(e) => setUseCustomRounds(e.target.checked)}
              />
              {t('step2.customToggle')}
            </label>
          </div>

          {useCustomRounds ? (
            <div>
              <div className="mb-2 flex items-baseline gap-2">
                <span className="font-mono text-2xl font-bold">{customMaxRounds}</span>
                <span className="text-xs text-muted-foreground">{t('step2.roundsUnit')}</span>
                <span className="ml-auto text-[11px] text-muted-foreground">
                  {t('step2.estimatedDuration', { minutes: Math.round(customMaxRounds * 0.6) })}
                </span>
              </div>
              <input
                type="range"
                min={10}
                max={autoGeneratedRounds}
                step={5}
                value={customMaxRounds}
                onChange={(e) => setCustomMaxRounds(Number(e.target.value))}
                className="w-full accent-[#FF5722]"
              />
              <div className="flex justify-between text-[10px] text-muted-foreground">
                <span>10</span>
                <button onClick={() => setCustomMaxRounds(40)} className="hover:text-foreground">
                  {t('step2.recommendedRounds', { rounds: 40 })}
                </button>
                <span>{autoGeneratedRounds}</span>
              </div>
            </div>
          ) : (
            <div className="flex items-center gap-4">
              <div className="flex items-baseline gap-1">
                <span className="font-mono text-2xl font-bold">{autoGeneratedRounds}</span>
                <span className="text-xs text-muted-foreground">{t('step2.roundsUnit')}</span>
              </div>
              <span className="flex items-center gap-1 rounded bg-muted px-2 py-1 text-[10px]">
                <Clock className="h-3 w-3" />
                {t('step2.estimatedDurationFull', { minutes: Math.round(autoGeneratedRounds * 0.6) })}
              </span>
              <button
                onClick={() => setUseCustomRounds(true)}
                className="ml-auto text-[11px] text-[#FF5722] hover:underline"
              >
                {t('step2.customTip')} ➝
              </button>
            </div>
          )}
        </div>
      )}

      <div className="flex gap-3">
        <button
          onClick={onBack}
          className="flex-1 rounded border py-3 text-xs font-semibold transition hover:bg-accent"
        >
          ← {t('step2.backToGraphBuild')}
        </button>
        <button
          onClick={onStart}
          disabled={phase < 4}
          className="flex-1 rounded bg-foreground py-3 text-xs font-semibold text-background transition hover:opacity-80 disabled:cursor-not-allowed disabled:opacity-40"
        >
          {t('step2.startDualWorldSim')} ➝
        </button>
      </div>
    </StepCard>
  )
}
