import { useTranslation } from 'react-i18next'
import { Clock } from 'lucide-react'

import { StepCard } from '@/components/StepCard'
import { Button } from '@/components/ui/button'
import { Checkbox } from '@/components/ui/checkbox'
import { Label } from '@/components/ui/label'
import { Slider } from '@/components/ui/slider'

interface Props {
  phase: number
  hasConfig: boolean
  autoGeneratedRounds: number | null
  useCustomRounds: boolean
  setUseCustomRounds: (v: boolean) => void
  customMaxRounds: number
  setCustomMaxRounds: (v: number) => void
  onBack: () => void
  onStart: () => void
}

/** 步骤 05：准备完成（模拟轮数配置 + 开始/返回）。 */
export function SetupCompleteCard({
  phase,
  hasConfig,
  autoGeneratedRounds,
  useCustomRounds,
  setUseCustomRounds,
  customMaxRounds,
  setCustomMaxRounds,
  onBack,
  onStart,
}: Props) {
  const { t } = useTranslation()

  return (
    <StepCard
      num="05"
      title={t('step2.setupComplete')}
      status={phase >= 4 ? 'processing' : 'pending'}
      statusText={phase >= 4 ? t('step1.inProgress') : t('common.pending')}
      active={phase === 4}
      apiNote="POST /api/simulation/start"
      description={t('step2.setupCompleteDesc')}
    >
      {hasConfig && autoGeneratedRounds && (
        <div className="mb-4 rounded-md border p-4">
          <div className="mb-3 flex items-start justify-between gap-2">
            <div>
              <span className="block text-xs font-semibold">{t('step2.roundsConfig')}</span>
            </div>
            <Label className="flex cursor-pointer items-center gap-2 text-xs">
              <Checkbox
                checked={useCustomRounds}
                onCheckedChange={(c) => setUseCustomRounds(c === true)}
              />
              {t('step2.customToggle')}
            </Label>
          </div>

          {useCustomRounds ? (
            <div>
              <div className="mb-2 flex items-baseline gap-2">
                <span className="font-mono text-2xl font-bold">{customMaxRounds}</span>
                <span className="text-muted-foreground text-xs">{t('step2.roundsUnit')}</span>
                <span className="text-muted-foreground ml-auto text-[11px]">
                  {t('step2.estimatedDuration', { minutes: Math.round(customMaxRounds * 0.6) })}
                </span>
              </div>
              <Slider
                min={10}
                max={autoGeneratedRounds}
                step={5}
                value={[customMaxRounds]}
                onValueChange={(v) => setCustomMaxRounds(v[0])}
              />
              <div className="text-muted-foreground mt-1 flex justify-between text-[10px]">
                <span>10</span>
                <button onClick={() => setCustomMaxRounds(40)} className="hover:text-foreground">
                  {t('step2.recommendedRounds', { rounds: 40 })}
                </button>
                <span>{autoGeneratedRounds}</span>
              </div>
            </div>
          ) : (
            <div className="flex items-center gap-4">
              <div className="flex items-baseline gap-1">
                <span className="font-mono text-2xl font-bold">{autoGeneratedRounds}</span>
                <span className="text-muted-foreground text-xs">{t('step2.roundsUnit')}</span>
              </div>
              <span className="bg-muted flex items-center gap-1 rounded px-2 py-1 text-[10px]">
                <Clock className="h-3 w-3" />
                {t('step2.estimatedDurationFull', {
                  minutes: Math.round(autoGeneratedRounds * 0.6),
                })}
              </span>
              <button
                onClick={() => setUseCustomRounds(true)}
                className="ml-auto text-[11px] text-[#FF5722] hover:underline"
              >
                {t('step2.customTip')} ➝
              </button>
            </div>
          )}
        </div>
      )}

      <div className="flex gap-3">
        <Button variant="outline" className="flex-1" onClick={onBack}>
          ← {t('step2.backToGraphBuild')}
        </Button>
        <Button className="flex-1" disabled={phase < 4} onClick={onStart}>
          {t('step2.startDualWorldSim')} ➝
        </Button>
      </div>
    </StepCard>
  )
}
